---
title: "Manipulating Data : Tutorial"
author: "Jeffrey Blanchard"
date: "9/9/2020"
output: html_document
---



From https://datacarpentry.org/R-ecology-lesson/03-dplyr.html

```{r}
library(tidyverse)
```

```{r}
surveys <- read_csv("data/portal_data_joined.csv")
```

```{r}
## inspect the data
str(surveys)
```

```{r}
head(select(surveys, plot_id, species_id, weight))
```

```{r}
head(select(surveys, -record_id, -species_id))
```

```{r}
head(filter(surveys, year == 1995))
```


```{r}
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
surveys_sml
```

```{r}
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
surveys_sml
```

```{r}
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
```


```{r}
surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

surveys_sml
```

### Challenge 1

```{r}
surveys_b_1995 <- surveys %>%
    filter(year < 1995) %>%
    select(year, sex, weight)
head(surveys_b_1995)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

### Challenge 2

```{r}
surveys_hindfoot_cm <- surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    mutate(hindfoot_cm = hindfoot_length / 10) %>%
    filter(hindfoot_cm < 3) %>%
    select(species_id, hindfoot_cm)
surveys_hindfoot_cm
```

```{r}
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```

```{r}
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>% 
  tail()
```


```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)
```


```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))
```


```{r}
surveys %>%
    count(sex)
```

```{r}
surveys %>%
    group_by(sex) %>%
    summarise(count = n())
```

```{r}
surveys %>%
    count(sex, sort = TRUE) 
```

```{r}
surveys %>%
  count(sex, species) 
```

```{r}
surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```

### Challenge 3

```{r}
#1 How many animals were caught in each plot_type surveyed?
surveys %>%
    count(plot_type) 
```

```{r}
#2   Use group_by() and summarize() to find the mean, min, and max hindfoot length for each species (using species_id). Also add the number of observations (hint: see ?n).
surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    group_by(species_id) %>%
    summarize(
        mean_hindfoot_length = mean(hindfoot_length),
        min_hindfoot_length = min(hindfoot_length),
        max_hindfoot_length = max(hindfoot_length),
        n = n()
    )

```

```{r}
# 3 What was the heaviest animal measured in each year? Return the columns year, genus, species_id, and weight.
surveys %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(year, genus, species, weight) %>%
    arrange(year)
```

```{r}
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))
str(surveys_gw)
```

```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
```


```{r}
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```

```{r}
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)
str(surveys_gather)
```

```{r}
surveys_spread %>%
  gather(key = "genus", value = "mean_weight", Baiomys:Spermophilus) %>%
  head()
```


### Challenge 4 

```{r}
#4 Spread the surveys data frame with year as columns, plot_id as rows, and the number of genera per plot as the values. You will need to summarize before reshaping, and use the function n_distinct() to get the number of unique genera within a particular chunk of data. It’s a powerful function! See ?n_distinct for more.

surveys_spread_genera <- surveys %>%
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)
head(surveys_spread_genera)
```

```{r}
#2 Now take that data frame and gather() it again, so each row is a unique plot_id by year combination.
surveys_spread_genera %>%
  gather("year", "n_genera", -plot_id)
```

```{r}
#3 The surveys data set has two measurement columns: hindfoot_length and weight. This makes it difficult to do things like look at the relationship between mean values of each measurement per year in different plot types. Let’s walk through a common solution for this type of problem. First, use gather() to create a dataset where we have a key column called measurement and a value column that takes on the value of either hindfoot_length or weight. Hint: You’ll need to specify which columns are being gathered.

surveys_long <- surveys %>%
  gather("measurement", "value", hindfoot_length, weight)
head(surveys_long)
```

```{r}
#4 With this new data set, calculate the average of each measurement in each year for each different plot_type. Then spread() them into a data set with a column for hindfoot_length and weight. Hint: You only need to specify the key and value columns for spread()

surveys_long %>%
  group_by(year, measurement, plot_type) %>%
  summarize(mean_value = mean(value, na.rm=TRUE)) %>%
  spread(measurement, mean_value)
```

```{r}
surveys_complete <- surveys %>%
  filter(!is.na(weight),           # remove missing weight
         !is.na(hindfoot_length),  # remove missing hindfoot_length
         !is.na(sex))                # remove missing sex
```

```{r}
## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)
dim(surveys_complete)
```

```{r}
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```

